apiVersion: v1
kind: ConfigMap
metadata:
  name: index
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to Lviv JavaClub!</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>Welcome to Lviv JavaClub!</h1>
    <p>If you see this page, the Lviv Java club event have started and you are learning something new.</p>

    <p>For more information please refer to
    <a href="https://www.javaclub.lviv.ua/">javaclub.lviv.ua</a>.<br/>

    <p><em>Thank you for using attending Lviv Java club.</em></p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: index-page
      volumes:
      - name: index-page
        configMap:
          name: index
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
